### PR TITLE
chore(update): add hard coded full jspm install script

### PR DESCRIPTION
**Pull request by douglasduteil**
This might be optional.
I just don't know how to force jspm to change the `package.json` and update to the latest available version. 
Furthermore I don't know if the updating process should  change the `jspm.config.js`.

@guybedford I'm waiting for your feedback to go forward here.
Thanks.

### CODE REVIEW

**Comment by guybedford** [comment]
This would just be `jspm update`. jspm doesn't bump the package.json (currently) but will bump all the jspm.config.js versions then.

**Comment by douglasduteil** [comment]
Alright. But is it enough ? 
Don't you want to bump some dependencies in the `packages.json` ?
Maybe not the majority of them be `core-js` at least no ?

FYI here is the git diff result of running the update script :  

```diff 
{
   "jspm": {
     "dependencies": {
-      "babel": "npm:babel-core@^6.3.17",
-      "babel-helpers": "npm:babel-helpers@^6.3.13",
-      "babel-plugin-check-es2015-constants": "npm:babel-plugin-check-es2015-constants@^6.3.13",
-      "babel-plugin-external-helpers": "npm:babel-plugin-external-helpers@^6.3.13",
-      "babel-plugin-transform-es2015-arrow-functions": "npm:babel-plugin-transform-es2015-arrow-functions@^6.3.13",
-      "babel-plugin-transform-es2015-block-scoped-functions": "npm:babel-plugin-transform-es2015-block-scoped-functions@^6.3.13",
-      "babel-plugin-transform-es2015-block-scoping": "npm:babel-plugin-transform-es2015-block-scoping@^6.3.13",
-      "babel-plugin-transform-es2015-classes": "npm:babel-plugin-transform-es2015-classes@^6.3.15",
-      "babel-plugin-transform-es2015-computed-properties": "npm:babel-plugin-transform-es2015-computed-properties@^6.3.13",
-      "babel-plugin-transform-es2015-destructuring": "npm:babel-plugin-transform-es2015-destructuring@^6.3.15",
-      "babel-plugin-transform-es2015-for-of": "npm:babel-plugin-transform-es2015-for-of@^6.3.13",
-      "babel-plugin-transform-es2015-function-name": "npm:babel-plugin-transform-es2015-function-name@^6.3.19",
-      "babel-plugin-transform-es2015-literals": "npm:babel-plugin-transform-es2015-literals@^6.3.13",
-      "babel-plugin-transform-es2015-modules-systemjs": "npm:babel-plugin-transform-es2015-modules-systemjs@^6.3.13",
-      "babel-plugin-transform-es2015-object-super": "npm:babel-plugin-transform-es2015-object-super@^6.3.13",
-      "babel-plugin-transform-es2015-parameters": "npm:babel-plugin-transform-es2015-parameters@^6.3.18",
-      "babel-plugin-transform-es2015-shorthand-properties": "npm:babel-plugin-transform-es2015-shorthand-properties@^6.3.13",
-      "babel-plugin-transform-es2015-spread": "npm:babel-plugin-transform-es2015-spread@^6.3.14",
-      "babel-plugin-transform-es2015-sticky-regex": "npm:babel-plugin-transform-es2015-sticky-regex@^6.3.13",
-      "babel-plugin-transform-es2015-template-literals": "npm:babel-plugin-transform-es2015-template-literals@^6.3.13",
-      "babel-plugin-transform-es2015-typeof-symbol": "npm:babel-plugin-transform-es2015-typeof-symbol@^6.3.13",
-      "babel-plugin-transform-es2015-unicode-regex": "npm:babel-plugin-transform-es2015-unicode-regex@^6.3.13",
-      "babel-plugin-transform-regenerator": "npm:babel-plugin-transform-regenerator@^6.3.18",
-      "babel-plugin-transform-runtime": "npm:babel-plugin-transform-runtime@^6.3.13",
+      "babel": "npm:babel-core@^6.9.1",
+      "babel-helpers": "npm:babel-helpers@^6.8.0",
+      "babel-plugin-check-es2015-constants": "npm:babel-plugin-check-es2015-constants@^6.8.0",
+      "babel-plugin-external-helpers": "npm:babel-plugin-external-helpers@^6.8.0",
+      "babel-plugin-transform-es2015-arrow-functions": "npm:babel-plugin-transform-es2015-arrow-functions@^6.8.0",
+      "babel-plugin-transform-es2015-block-scoped-functions": "npm:babel-plugin-transform-es2015-block-scoped-functions@^6.8.0",
+      "babel-plugin-transform-es2015-block-scoping": "npm:babel-plugin-transform-es2015-block-scoping@^6.9.0",
+      "babel-plugin-transform-es2015-classes": "npm:babel-plugin-transform-es2015-classes@^6.9.0",
+      "babel-plugin-transform-es2015-computed-properties": "npm:babel-plugin-transform-es2015-computed-properties@^6.8.0",
+      "babel-plugin-transform-es2015-destructuring": "npm:babel-plugin-transform-es2015-destructuring@^6.9.0",
+      "babel-plugin-transform-es2015-for-of": "npm:babel-plugin-transform-es2015-for-of@^6.8.0",
+      "babel-plugin-transform-es2015-function-name": "npm:babel-plugin-transform-es2015-function-name@^6.9.0",
+      "babel-plugin-transform-es2015-literals": "npm:babel-plugin-transform-es2015-literals@^6.8.0",
+      "babel-plugin-transform-es2015-modules-systemjs": "npm:babel-plugin-transform-es2015-modules-systemjs@^6.9.0",
+      "babel-plugin-transform-es2015-object-super": "npm:babel-plugin-transform-es2015-object-super@^6.8.0",
+      "babel-plugin-transform-es2015-parameters": "npm:babel-plugin-transform-es2015-parameters@^6.9.0",
+      "babel-plugin-transform-es2015-shorthand-properties": "npm:babel-plugin-transform-es2015-shorthand-properties@^6.8.0",
+      "babel-plugin-transform-es2015-spread": "npm:babel-plugin-transform-es2015-spread@^6.8.0",
+      "babel-plugin-transform-es2015-sticky-regex": "npm:babel-plugin-transform-es2015-sticky-regex@^6.8.0",
+      "babel-plugin-transform-es2015-template-literals": "npm:babel-plugin-transform-es2015-template-literals@^6.8.0",
+      "babel-plugin-transform-es2015-typeof-symbol": "npm:babel-plugin-transform-es2015-typeof-symbol@^6.8.0",
+      "babel-plugin-transform-es2015-unicode-regex": "npm:babel-plugin-transform-es2015-unicode-regex@^6.8.0",
+      "babel-plugin-transform-regenerator": "npm:babel-plugin-transform-regenerator@^6.9.0",
+      "babel-plugin-transform-runtime": "npm:babel-plugin-transform-runtime@^6.9.0",
       "babel-preset-stage-1": "npm:babel-preset-stage-1@^6.5.0",
       "babel-preset-stage-2": "npm:babel-preset-stage-2@^6.5.0",
-      "babel-preset-stage-3": "npm:babel-preset-stage-3@^6.3.13",
-      "core-js": "npm:core-js@^1.2.6",
+      "babel-preset-stage-3": "npm:babel-preset-stage-3@^6.5.0",
+      "core-js": "npm:core-js@^2.4.0",
       "regenerator-runtime": "npm:regenerator-runtime@^0.9.5"
     },
}
```

**Comment by guybedford** [comment]
Yes it's fine. Bumping package.json should be a jspm feature anyway. We could make the default for `jspm update` to bump the package.json versions, or we could have a flag for this.

**Comment by douglasduteil** [comment]
Alright

**Comment by douglasduteil** [comment]
We are close to a new release :)
I will bump the `npm:core-js` to `2.4.0` (cf. https://github.com/babel/babel/releases/tag/v6.9.0)

**Pull request closed without merging**
